### ISSUE TITLE
List out dependencies

### ISSUE THREAD

**Issue by pbnjeff89** [masonlab/labdrivers#10]
Reason: If we have new computers it would be a good idea to have a list of required packages so that we minimize the time to figure out why `labdrivers` is not working.

This list should include packages like:

1. pyvisa

2. PyDAQmx

**Comment by hinnefe2** [comment]
This is kind of the point of the `environment.yml` file, though that is specific to [conda](https://conda.io/docs/user-guide/overview.html). Generic python uses `requirements.txt` along with [pip](https://pip.pypa.io/en/stable/user_guide/#requirements-files), so if you all aren't using conda then you could convert that file to a `requirements.txt`.

**Comment by pbnjeff89** [comment]
@hinnefe2 Ah, I guess I skipped over that. I will just convert that into a `requirements.txt` later since I'm not entirely sure if future users would think to install `conda`. I'll close this issue once I do that. Thanks for pointing that out!

**Comment by hinnefe2** [comment]
Another thing I just thought of: if you drop the `environment.yml` file it probably makes sense to drop the conda install section from the [docs](https://github.com/masonlab/labdrivers/blob/master/docs/installation.rst#installing-to-a-conda-environment) so they stay up to date.

**Comment by pbnjeff89** [comment]
Mostly a TODO for myself for properly generating `requirements.txt`:

- Create a virtual environment with all the necessary packages

- Use `pip freeze > requirements.txt` to generate the file

**Comment by pbnjeff89** [comment]
Closing this too. Don't think this is something to worry about anymore
