### ISSUE TITLE
Read DLL builtin functions in qdinstruments.dll

### ISSUE THREAD

**Issue by YuanJ-i** [masonlab/labdrivers#34]
How can you know the c# class name in this dll? Where can I have the reference to the dll biultin functions? I did not find help doc in QD official website.
I also use the DUMPBIN tool provided by VS, but it seems there is no useful info.

**Comment by hinnefe2** [comment]
I think the information about the DLL came from decompiling it using something like https://www.jetbrains.com/decompiler/

**Comment by YuanJ-i** [comment]
It works, thank you for your reply
